target ‘GithubDemoTest’ do
    
pod 'Masonry'           #自动布局
pod 'pop', '~> 1.0'     #Facebook 动画库
pod 'SDWebImage'        #图片缓存
pod 'NJKWebViewProgress'



  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end

end